#!/usr/bin/env python3
"""Regenerates the static pages, sitemap.xml, robots.txt and manifest.json.
Domain/version come from js/config.js (single source). Run: python3 tools/build.py
Articles in posts/ are NOT overwritten if they already exist."""
import re, json, os
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(R)
cfg = open('js/config.js').read()
g = lambda k: re.search(k + r':\s*"([^"]*)"', cfg).group(1)
D, VER, GH = g('domain').rstrip('/'), g('version'), g('github')
APK = g('apkUrl')  # baked into HTML so the button works even without JS
NAV = [('index','Home'),('features','Features'),('download','Download'),('premium','Premium'),('blog','Blog'),('about','About')]
BTN = lambda t='Download FocusLock', c='': f'<a class="btn {c}" data-apk href="{APK}">{t}</a>'
SW = {"@context":"https://schema.org","@type":"SoftwareApplication","name":"FocusLock","operatingSystem":"Android","applicationCategory":"ProductivityApplication","softwareVersion":VER,"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"url":D+"/"}
def head(t, d, path, ld, base='', img='assets/images/bg-cyber.webp', typ='website'):
    u = f'{D}/{path}'; im = f'{D}/{img}'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{t}</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><meta name="theme-color" content="#070b12">
<meta property="og:type" content="{typ}"><meta property="og:site_name" content="FocusLock"><meta property="og:title" content="{t}"><meta property="og:description" content="{d}"><meta property="og:url" content="{u}"><meta property="og:image" content="{im}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{t}"><meta name="twitter:description" content="{d}"><meta name="twitter:image" content="{im}">
<link rel="icon" href="{base}favicon/favicon.ico" sizes="any"><link rel="icon" type="image/png" href="{base}favicon/favicon-32.png"><link rel="apple-touch-icon" href="{base}favicon/apple-touch-icon.png"><link rel="manifest" href="{base}manifest.json">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700&family=Figtree:wght@400;600&display=swap">
<link rel="stylesheet" href="{base}css/style.css"><script type="application/ld+json">{json.dumps(ld)}</script></head>'''
def header(cur, base=''):
    li = ''.join(f'<li><a href="{base}{k}.html"{" aria-current=page" if k==cur else ""}>{n}</a></li>' for k,n in NAV)
    return f'''<body data-base="{base}"><header><div class="w nav"><a class="logo" href="{base}index.html"><img src="{base}assets/icons/icon-192.png" width="32" height="32" alt="">FocusLock</a>
<nav aria-label="Main"><ul id="menu">{li}</ul></nav><a class="btn sm" data-apk href="{APK}">Download</a><button id="mb" aria-expanded="false" aria-controls="menu" aria-label="Menu">☰</button></div></header><main>'''
def footer(base='', blog=False):
    L = lambda p,n: f'<a href="{base}{p}.html">{n}</a>'
    return f'''</main><footer><div class="w fg"><div><h3>FocusLock</h3><p>Set limits for distracting apps, lock them when time is up, and unlock only on purpose. Made for Android.</p></div>
<div><h3>Product</h3>{L('features','Features')}{L('download','Download')}{L('premium','Premium')}</div>
<div><h3>Resources</h3>{L('blog','Blog')}{L('about','About')}<a data-gh href="{GH}" target="_blank" rel="noopener">GitHub</a></div>
<div><h3>Legal</h3>{L('privacy','Privacy policy')}{L('terms','Terms')}<a data-mail href="{base}about.html#contact">Contact</a></div></div>
<div class="w" style="margin-top:28px">© <span data-cfg="year">2026</span> FocusLock by <a data-dev href="https://zihad07.vercel.app" target="_blank" rel="noopener">Zihad</a>.</div></footer>
<script src="{base}js/config.js"></script><script src="{base}js/main.js"></script>{f'<script src="{base}js/blog.js" data-base="{base}"></script>' if blog else ''}</body></html>'''
CTA = '<section><div class="w"><div class="cta"><h2>Take back your time</h2><p>Free for Android. No account needed.</p>' + BTN() + '</div></section>'.replace('</section>','</div>') + '</section>' if False else '<section><div class="w"><div class="cta"><h2>Take back your time</h2><p>Free for Android. No account needed.</p>' + BTN() + '</div></div></section>'
def phone(kind, base=''):
    alt = {'home':'FocusLock Home screen','block':'FocusLock lock screen shown when a daily limit is reached'}[kind]
    ld = '' if kind=='home' else ' loading="lazy"'
    return f'<div class="phone"><img src="{base}assets/screenshots/{kind}.png" width="720" height="1600" alt="{alt}"{ld} onerror="this.parentNode.hidden=true"></div>'
card = lambda h, p: f'<div class="card"><h3>{h}</h3><p>{p}</p></div>'
POSTS = [
 ('reduce-screen-time','7 simple ways to reduce screen time','Practical steps to spend less time on distracting apps, and how app limits can help.','Habits','2026-09-28','bg-aurora',
  '<p>Most of us do not plan to lose an hour to a feed. It just happens. These steps make that harder.</p><h2>1. Pick the apps that cost you most</h2><p>Check your usage stats and choose the two or three apps that eat the most time. Start with those, not everything.</p><h2>2. Set a daily limit per app</h2><p>A limit turns a vague wish into a number. In FocusLock you set a daily time limit for each app you choose.</p><h2>3. Add friction</h2><p>When the limit is reached, make opening the app slower. See <a href="why-unlocking-should-take-effort.html">why unlocking should take effort</a>.</p><h2>4. Protect blocks of deep work</h2><p>Plan focus sessions with no notifications. Read <a href="run-a-deep-focus-session.html">how to run a deep focus session</a>.</p><h2>5. Track it weekly</h2><p>Look at your trend once a week. Small drops add up.</p>'),
 ('why-unlocking-should-take-effort','Why unlocking an app should take a little effort','A short pause between the urge and the app is often enough to change your mind.','Focus','2026-09-30','bg-cyber',
  '<p>Impulse opens are fast. A small barrier slows them down enough for you to ask: do I really want this?</p><h2>Make the pause useful</h2><p>FocusLock offers four unlock challenges: a math problem, a focus countdown, typing a sentence, or entering your PIN. You choose which ones are on.</p><h2>Keep real emergencies easy</h2><p>FocusLock never blocks the phone dialer or emergency calls, and it has daily emergency unlocks for urgent needs.</p><p>Next: <a href="reduce-screen-time.html">7 ways to reduce screen time</a>.</p>'),
 ('run-a-deep-focus-session','How to run a deep focus session','A simple routine for 25 to 120 minutes of work without distractions.','Productivity','2026-10-01','bg-ocean',
  '<p>Deep work needs a clear start, a clear end, and fewer interruptions in between.</p><h2>Before you start</h2><p>Pick one task and one duration. FocusLock Focus mode lets you choose the length of your session.</p><h2>During the session</h2><p>Restricted apps stay blocked until the session ends. FocusLock can also use Do Not Disturb to silence notifications, if you allow that permission.</p><h2>After</h2><p>Take a real break away from the screen. Then plan the next one. See also <a href="reduce-screen-time.html">reduce screen time</a>.</p>')]
def post_page(p):
    s,t,d,c,dt,im,body = p; path=f'posts/{s}.html'
    ld={"@context":"https://schema.org","@type":"Article","headline":t,"description":d,"datePublished":dt,"image":f"{D}/assets/images/{im}.webp","author":{"@type":"Person","name":"Zihad"},"publisher":{"@type":"Organization","name":"FocusLock"},"mainEntityOfPage":f"{D}/{path}"}
    return head(f'{t} | FocusLock Blog',d,path,ld,'../',f'assets/images/{im}.webp','article')+header('blog','../')+f'<article><section><div class="w prose"><p class="meta">{c} · {dt}</p><h1 style="font-size:clamp(2rem,5vw,3rem)">{t}</h1><img src="../assets/images/{im}.webp" alt="" width="540" height="300" style="width:100%;height:260px;object-fit:cover;border-radius:18px;margin:20px 0">{body}</div></section></article><section><div class="w"><h2>Related articles</h2><div class="grid" id="related"></div></div></section>'+CTA+footer('../',True)
def page(name,t,d,body,ld=None,blog=False):
    open(f'{name}.html','w').write(head(t,d,f'{name}.html' if name!='index' else '',ld or SW)+header(name)+body+footer('',blog))
plans = '<div class="grid" data-plans></div>'
page('index','FocusLock: App limits and focus for Android','Set daily limits for distracting apps, lock them when time is up, and unlock only on purpose. Free Android app.',f'''
<section><div class="w hero"><div><h1>Make distraction harder. Make focus easier.</h1><p>FocusLock puts a calm barrier between you and the apps that waste your time. Choose the apps, set the limits, and stay on track.</p><div class="row">{BTN()}<a class="btn g" href="features.html">Explore features</a></div></div><div class="rings">{phone('home')}</div></div></section>
<section><div class="w"><h2>Why FocusLock</h2><div class="grid">{card('Your data stays on your phone','Usage records, limits and goals are stored on the device. No account is needed.')}{card('Built for intent','Time is not just cut off. Unlocking takes a deliberate step you choose.')}{card('Safe by design','Phone calls and emergency calls are never blocked, and emergency unlocks exist.')}</div></div></section>
<section><div class="w"><h2>What it does</h2><div class="grid">{card('App time limits','Set a daily limit for each app you choose.')}{card('Automatic app locking','When the limit is reached, FocusLock shows a block screen over the app.')}{card('Focus challenges','Unlock with a math problem, a countdown, typing a sentence, or a PIN.')}{card('Usage tracking','See screen time, trends, goals and streaks.')}</div></div></section>
<section><div class="w"><h2>How it works</h2><ol class="steps"><li><span><b style="color:var(--t)">Pick your apps.</b> Choose the apps you want to control and set a daily limit.</span></li><li><span><b style="color:var(--t)">FocusLock keeps watch.</b> It notices when a limited app is opened and warns you as the limit gets close.</span></li><li><span><b style="color:var(--t)">Time is up, a pause begins.</b> A block screen appears. Unlock only by completing a challenge.</span></li></ol></div></section>
<section><div class="w split"><div><h2>A calm block screen</h2><p>When your limit is reached you see a clear message, not a punishment. Wait, breathe, or complete a challenge.</p><a class="btn g" href="features.html">See all features</a></div>{phone('block')}</div></section>
<section><div class="w"><h2>Premium removes ads</h2><p>The free app shows ads. Premium turns them off. Pay with USDT through Binance Pay.</p>{plans}<div class="row"><a class="btn g" href="premium.html">How Premium works</a></div></div></section>
<section><div class="w"><h2>Latest from the blog</h2><div class="grid" id="latest"></div></div></section>{CTA}''',blog=True)
page('features','FocusLock Features: limits, locking, challenges','Everything FocusLock does: app time limits, automatic locking, unlock challenges, usage tracking, notifications, themes and privacy.',f'''
<section><div class="w"><h1>Features</h1><p>FocusLock is a focused set of tools. Here is what is in the app today.</p></div></section>
<section><div class="w split"><div class="prose"><h2>App time limits</h2><p>Choose apps and set a daily allowance for each. You can also use schedules to restrict apps at set times, and Focus mode to lock distractions for a session of your chosen length.</p><h2>Automatic app locking</h2><p>FocusLock uses Android Accessibility to see which app is in front, then shows a block screen over it when the limit is reached. Optional Escape Prevention helps stop impulsive force-stops and uninstalls while protection is on.</p></div>{phone('block')}</div></section>
<section><div class="w prose"><h2>Focus and unlock challenges</h2><p>Four ways to earn extra access: a mental math problem, a patience countdown, typing a sentence exactly, or your own PIN. Emergency unlocks give short access when something is truly urgent.</p><h2>Usage tracking</h2><p>FocusLock reads Android usage access to show screen time, most distracting apps, insights, goals, streaks and achievement cards you can share.</p><h2>Notifications</h2><p>Get a heads-up when you are close to a limit, and an alert when an app is locked. During Focus mode, FocusLock can silence other notifications with Do Not Disturb, if you allow it.</p><h2>Customization</h2><p>Pick from six animated background themes: Cherry Blossom, Sakura Lake, Autumn Leaves, Cyber Rain, Aurora Forest and Deep Ocean. The app supports English, Bangla, Spanish, French, Arabic and Portuguese.</p><h2>Privacy</h2><p>Your usage data is stored on your device. You can export a backup file or restore one from Settings. Read the full <a href="privacy.html">privacy policy</a>.</p></div></section>{CTA}''')
page('download','Download FocusLock for Android (APK)','Download the latest FocusLock APK for Android. Version, size, requirements, install steps and help.',f'''
<section><div class="w hero"><div><h1>Download FocusLock for Android</h1><p>Free. Get the APK, install it, and set your first limit in a minute.</p><div class="row"><a class="btn" data-apk href="{APK}">Download APK <span data-cfg="size"></span></a></div><p style="margin-top:12px;font-size:.95rem">Download not starting? <a data-apk href="{APK}">Open the direct link</a>.</p></div><div class="grid"><div class="card"><small>Version</small><h3><span data-cfg="version"></span> (build <span data-cfg="build"></span>)</h3></div><div class="card"><small>Size</small><h3 data-cfg="size"></h3></div><div class="card"><small>Released</small><h3 data-cfg="date"></h3></div><div class="card"><small>Requires</small><h3 data-cfg="android"></h3></div></div></div></section>
<section><div class="w prose"><h2>Install</h2><ol class="steps"><li><span>Tap Download APK. Your browser may warn that this type of file can be harmful. Choose to keep it.</span></li><li><span>Open the file. If asked, allow your browser to install unknown apps.</span></li><li><span>Install and open FocusLock.</span></li><li><span>Grant the permissions below when the app asks.</span></li></ol>
<h2>Permissions</h2><ul><li><b>Usage access</b>: to measure how long you use each app.</li><li><b>Accessibility service</b>: to detect which app is open and show the lock screen. It is not used to read your messages or passwords.</li><li><b>Display over other apps</b>: to show the block screen.</li><li><b>Notifications</b>: for limit warnings and focus alerts.</li><li><b>Do Not Disturb access (optional)</b>: to silence notifications during Focus mode.</li><li><b>Internet</b>: for ads in the free version and for Premium payment checks.</li></ul>
<h2>Release history</h2><div class="card"><h3>v<span data-cfg="build"></span> · <span data-cfg="version"></span></h3><p>Latest release, <span data-cfg="date"></span>. Older releases are not listed here yet. See <a data-gh href="{GH}">GitHub</a> for updates.</p></div>
<h2>Help</h2><details><summary>The app will not install</summary><p>Check that you have {'Android 7.0'} or newer and enough free space. Allow installs from unknown apps for your browser or file manager.</p></details><details><summary>The block screen does not appear</summary><p>Open Settings, then Permission Center, and make sure Usage access, Accessibility and Display over other apps are all granted.</p></details><details><summary>The download does not start</summary><p>Try another browser or network. You can also get the file from <a data-gh href="{GH}">GitHub</a>.</p></details></div></section>{CTA}''')
page('premium','FocusLock Premium: remove ads','FocusLock Premium removes ads for a cleaner, distraction-free experience. Weekly $0.29, Monthly $0.49, Quarterly $1.50, Yearly $5.',f'''
<section><div class="w"><h1>FocusLock Premium</h1><p>Premium removes advertisements from FocusLock. Nothing else changes. A cleaner app for a calmer mind.</p>{plans}</div></section>
<section><div class="w"><h2>Benefits</h2><div class="grid">{card('No advertisements','All ads are removed while Premium is active.')}{card('A cleaner experience','Fewer things on screen.')}{card('Distraction-free','Ads are the last thing a focus app should show.')}</div></div></section>
<section><div class="w prose"><h2>How payment works</h2><p>Payment is made with USDT through Binance Pay. Everything happens inside the app.</p><ol class="steps"><li><span>Choose a plan in FocusLock.</span></li><li><span>Complete the Binance payment for the exact amount.</span></li><li><span>Submit the transaction ID in the app.</span></li><li><span>The payment is verified.</span></li><li><span>Premium is activated.</span></li></ol><p>This website never asks for payment details, keys or wallet credentials.</p>
<h2>FAQ</h2><details><summary>Does Premium add features?</summary><p>No. Premium removes ads.</p></details><details><summary>Which currency do I pay in?</summary><p>USDT, through Binance Pay.</p></details><details><summary>My verification failed. What now?</summary><p>Check the amount, the currency and the recipient, wait for Binance to finish the payment, then try again.</p></details><details><summary>Can I get a refund?</summary><p>See the refund section in the <a href="terms.html">terms</a>.</p></details></div></section>{CTA}''',{"@context":"https://schema.org","@type":"WebPage","name":"FocusLock Premium"})
page('blog','FocusLock Blog: focus and screen time tips','Articles about reducing screen time, building focus habits and getting more from FocusLock.','''
<section><div class="w"><h1>Blog</h1><p>Short, practical reads on focus and screen time.</p><div id="feat" style="margin-bottom:24px"></div><label for="q" class="meta">Search articles</label><input id="q" type="search" placeholder="Search"><div class="pills" id="cats" role="group" aria-label="Categories"></div><div class="grid" id="list"></div><div class="row"><button class="btn g" id="more" type="button" hidden>Load more</button></div></div></section>'''+CTA,{"@context":"https://schema.org","@type":"Blog","name":"FocusLock Blog","url":D+"/blog.html"},True)
page('about','About FocusLock','FocusLock is an Android app that helps you control distracting apps and build better digital habits. Learn why it exists.',f'''
<section><div class="w prose"><h1>About FocusLock</h1><p>FocusLock is an Android app that creates a simple barrier between you and distracting apps.</p><h2>The problem</h2><p>Apps are built to keep you scrolling. Willpower alone often loses.</p><h2>Mission</h2><p>Make distraction harder and focus easier, without taking control away from you.</p><h2>Philosophy</h2><p>You set the rules. FocusLock helps you keep them when it matters.</p><h2>What makes it different</h2><ul><li>Unlocking takes a deliberate challenge you choose.</li><li>Your usage data stays on your device.</li><li>Calls and emergencies are never blocked.</li></ul><h2>Developer</h2><p>FocusLock is made by <a data-dev href="https://zihad07.vercel.app">Zihad</a>. Source and releases: <a data-gh href="{GH}">GitHub</a>.</p><h2 id="contact">Contact</h2><p>Email: <a data-mail href="#"><span data-cfg="email"></span></a></p></div></section>{CTA}''')
page('privacy','Privacy Policy | FocusLock','How FocusLock handles your data: what stays on your device, permissions, ads, and Premium payment checks.','''
<section><div class="w prose"><h1>Privacy policy</h1><p>Items marked [CONFIG] depend on your setup and should be reviewed before launch.</p>
<h2>Information collected</h2><p>FocusLock stores your app limits, usage statistics, goals, streaks and settings in a local database on your device. There is no account.</p>
<h2>Information not collected</h2><p>FocusLock does not read your messages, passwords or keystrokes, and does not upload your usage history to its own servers. Analytics collection is turned off in the app.</p>
<h2>Android permissions</h2><p>Usage access, Accessibility, Display over other apps, Notifications, optional Do Not Disturb, and Internet. See the <a href="download.html">download page</a> for what each is used for.</p>
<h2>App usage and accessibility data</h2><p>The Accessibility service is used to detect which app is in the foreground so the block screen can appear.</p>
<h2>Local storage and backups</h2><p>Data stays on your device. If you export a backup, the file is saved where you choose.</p>
<h2>Advertising</h2><p>The free version shows ads from Adsterra in embedded web views. Adsterra may collect data under its own policy. Premium removes ads. [CONFIG: confirm ad partners]</p>
<h2>Premium and payment information</h2><p>Payments are made in Binance Pay. When you submit a transaction ID, the app checks it with Binance. FocusLock does not receive your Binance login. Premium expiry and used transaction IDs are stored on your device.</p>
<h2>Third-party services</h2><p>Adsterra (ads) and Binance (payment checks).</p>
<h2>Data security</h2><p>Data is kept on your device and protected by Android. No method is completely secure.</p>
<h2>Children's privacy</h2><p>FocusLock is not directed to children under 13. [CONFIG: review for your region]</p>
<h2>Changes</h2><p>We may update this policy and will change the date below.</p><p>Last updated: <span data-cfg="date"></span></p>
<h2>Contact</h2><p><a data-mail href="about.html#contact"><span data-cfg="email"></span></a></p></div></section>''')
page('terms','Terms of Service | FocusLock','Terms for using FocusLock, including Premium purchases, Binance payment verification and refunds.','''
<section><div class="w prose"><h1>Terms of service</h1><p>Items marked [CONFIG] must be completed before launch.</p>
<h2>Acceptance of terms</h2><p>By using FocusLock you agree to these terms.</p><h2>Using FocusLock</h2><p>You may use FocusLock for personal digital wellbeing. You choose which apps and protections to enable.</p>
<h2>App functionality</h2><p>FocusLock limits and blocks apps you select. Optional protections can make it harder to disable the app during a session. Calls and emergency functions are not blocked.</p>
<h2>Premium purchases</h2><p>Premium removes ads for the plan length: 7, 30, 90 or 365 days. Prices are shown in the app and on the Premium page.</p>
<h2>Binance payment verification</h2><p>Pay the exact USDT amount through Binance Pay, then submit the transaction ID in the app. Premium activates after the payment is verified.</p>
<h2>Refund policy</h2><p>[CONFIG: add your refund policy here]</p>
<h2>Premium entitlement</h2><p>Premium is stored on your device and is active until the end of the plan period.</p>
<h2>Acceptable use</h2><p>Do not misuse FocusLock, tamper with payment checks, or reuse transaction IDs.</p>
<h2>Disclaimer</h2><p>FocusLock is provided as is, without warranties.</p><h2>Changes to terms</h2><p>We may update these terms. Continued use means you accept them.</p>
<h2>Contact</h2><p><a data-mail href="about.html#contact"><span data-cfg="email"></span></a></p></div></section>''')
os.makedirs('posts',exist_ok=True)
for p in POSTS:
    if not os.path.exists(f'posts/{p[0]}.html'): open(f'posts/{p[0]}.html','w').write(post_page(p))
if not os.path.exists('data/posts.json'):
    json.dump([{"title":p[1],"slug":p[0],"description":p[2],"category":p[3],"date":p[4],"image":f"assets/images/{p[5]}.webp","url":f"posts/{p[0]}.html"} for p in POSTS],open('data/posts.json','w'),indent=2)
urls=[''if k=='index' else k+'.html' for k,_ in NAV]+['privacy.html','terms.html']+['posts/'+x['slug']+'.html' for x in json.load(open('data/posts.json'))]
open('sitemap.xml','w').write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{D}/{u}</loc></url>' for u in urls)+'</urlset>')
open('robots.txt','w').write(f'User-agent: *\nAllow: /\nSitemap: {D}/sitemap.xml\n')
json.dump({"name":"FocusLock","short_name":"FocusLock","start_url":"/","display":"standalone","background_color":"#070b12","theme_color":"#070b12","icons":[{"src":"assets/icons/icon-192.png","sizes":"192x192","type":"image/png"},{"src":"assets/icons/icon-512.png","sizes":"512x512","type":"image/png"}]},open('manifest.json','w'),indent=2)
print('built',len(urls),'urls')
