#!/usr/bin/env python3
"""Rebuilds every page, the blog posts, sitemap.xml, robots.txt and manifest.json.
All changeable values live in js/config.js. Run on a computer: python3 tools/build.py"""
import re, json, os
R = os.path.dirname(os.path.dirname(os.path.abspath(__file__))); os.chdir(R)
cfg = open('js/config.js').read()
g = lambda k: re.search(k + r':\s*"([^"]*)"', cfg).group(1)
D, VER, GH, APK, MINA, DEV = g('domain').rstrip('/'), g('version'), g('github'), g('apkUrl'), g('minAndroid'), g('developerSite')
NAV = [('index','Home'),('features','Features'),('tour','App Tour'),('download','Download'),('premium','Premium'),('blog','Blog'),('about','About')]
SW = {"@context":"https://schema.org","@type":"SoftwareApplication","name":"FocusLock","operatingSystem":"Android","applicationCategory":"ProductivityApplication","softwareVersion":VER,"offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"url":D+"/"}
BTN = lambda t='Download FocusLock', c='': f'<a class="btn {c}" data-apk href="{APK}">{t}</a>'

def head(t, d, path, ld, base='', typ='website'):
    u = f'{D}/{path}'; im = f'{D}/assets/images/ogimg.jpg'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{t}</title><meta name="description" content="{d}"><link rel="canonical" href="{u}"><meta name="theme-color" content="#070b12">
<meta property="og:type" content="{typ}"><meta property="og:site_name" content="FocusLock"><meta property="og:title" content="{t}"><meta property="og:description" content="{d}"><meta property="og:url" content="{u}"><meta property="og:image" content="{im}">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{t}"><meta name="twitter:description" content="{d}"><meta name="twitter:image" content="{im}">
<link rel="icon" href="{base}favicon/favicon.ico" sizes="any"><link rel="icon" type="image/png" href="{base}favicon/favicon-32.png"><link rel="apple-touch-icon" href="{base}favicon/apple-touch-icon.png"><link rel="manifest" href="{base}manifest.json">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@600;700&family=Figtree:wght@400;600&display=swap">
<link rel="stylesheet" href="{base}css/style.css"><script type="application/ld+json">{json.dumps(ld)}</script></head>'''
def header(cur, base=''):
    li = ''.join(f'<li><a href="{base}{k}.html"{" aria-current=page" if k==cur else ""}>{n}</a></li>' for k,n in NAV)
    return f'''<body data-base="{base}"><header><div class="w nav"><a class="logo" href="{base}index.html"><img src="{base}assets/icons/icon-192.png" width="32" height="32" alt="">FocusLock</a>
<nav aria-label="Main"><ul id="menu">{li}</ul></nav><a class="btn sm" data-apk href="{APK}">Download</a><button id="mb" aria-expanded="false" aria-controls="menu" aria-label="Menu">☰</button></div></header><main>'''
def footer(base='', blog=False):
    L = lambda p,n: f'<a href="{base}{p}.html">{n}</a>'
    return f'''</main><footer><div class="w fg"><div><h3>FocusLock</h3><p>Set limits for distracting apps, lock them when time is up, and unlock only on purpose. Made for Android.</p></div>
<div><h3>Product</h3>{L('features','Features')}{L('tour','App Tour')}{L('download','Download')}{L('premium','Premium')}</div>
<div><h3>Resources</h3>{L('blog','Blog')}{L('faq','FAQ')}{L('about','About')}<a data-gh href="{GH}" target="_blank" rel="noopener">GitHub</a></div>
<div><h3>Legal</h3>{L('privacy','Privacy policy')}{L('terms','Terms')}<a data-mail href="{base}about.html#contact">Contact</a></div></div>
<div class="w copy">© <span data-cfg="year">2026</span> FocusLock by <a data-dev href="{DEV}" target="_blank" rel="noopener">Zihad</a>.</div></footer>
<script src="{base}js/config.js"></script><script src="{base}js/main.js"></script>{f'<script src="{base}js/blog.js" data-base="{base}"></script>' if blog else ''}</body></html>'''

# ---------- building blocks ----------
def phone(name, alt, base='', lazy=True):
    return f'<div class="phone"><img src="{base}assets/screenshots/{name}.webp" width="520" height="1040" alt="{alt}"{" loading=lazy" if lazy else ""} onerror="this.parentNode.hidden=true"></div>'
def shot(name, cap, alt):
    return f'<figure class="shot">{phone(name, alt)}<figcaption>{cap}</figcaption></figure>'
card = lambda h, p, i='': f'<div class="card">{f"<div class=ic>{i}</div>" if i else ""}<h3>{h}</h3><p>{p}</p></div>'
def head2(eyebrow, h, p=''): return f'<p class="eyebrow">{eyebrow}</p><h2>{h}</h2>' + (f'<p class="lead">{p}</p>' if p else '')
def det(q, a): return f'<details><summary>{q}</summary><p>{a}</p></details>'
def row(eyebrow, h, body, phones, rev=False):
    return f'<section><div class="w split{" rev" if rev else ""}"><div class="prose">{head2(eyebrow,h)}{body}</div><div class="duo">{phones}</div></div></section>'
CTA = f'<section><div class="w"><div class="cta"><h2>Take back your time</h2><p>Free for Android. No account needed.</p><div class="row c">{BTN()}<a class="btn g" href="tour.html">Take the app tour</a></div></div></div></section>'
def page(name, t, d, body, ld=None, blog=False):
    open(f'{name}.html','w').write(head(t,d,f'{name}.html' if name!='index' else '',ld or SW)+header(name)+body+footer('',blog))
def faq_ld(items): return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":re.sub('<[^>]+>','',a)}} for q,a in items]}

FAQ = [
 ("What is FocusLock?","FocusLock is a free Android app. You pick distracting apps, set a daily limit for each, and FocusLock puts a block screen over them when time is up."),
 ("Is FocusLock free?","Yes. The free version shows ads. Premium removes the ads and nothing else changes."),
 ("Do I need an account?","No. There is no sign-up. Your limits and usage data stay on your phone."),
 ("What permissions does it need, and why?","Usage access to measure app time, the Accessibility service to see which app is open, Display over other apps to show the block screen, and Notifications for warnings. Do Not Disturb access is optional and only used in Focus mode. See the <a href='privacy.html'>privacy page</a> for details."),
 ("Can I set different limits for different apps?","Yes. Every app has its own switch and its own daily limit. You can also use limit templates and schedules."),
 ("What happens when a limit is reached?","A block screen appears over the app. You can stay locked in, complete an unlock challenge, or use one of your limited emergency bypasses."),
 ("What are unlock challenges?","Short tasks that add a pause before you get more time: a mental math question, a 30-second patience countdown, typing a sentence exactly, or your own PIN. You choose what is turned on."),
 ("Does FocusLock block emergency calls?","No. Phone calls and emergency functions are not blocked, and there are daily emergency bypasses for urgent needs."),
 ("What does Premium do?","It removes all advertisements from FocusLock. Plans: Weekly $0.29, Monthly $0.49, Quarterly $1.50 and Yearly $5."),
 ("How does Premium payment work?","Choose a plan in the app, pay the exact USDT amount with Binance Pay, enter the transaction ID in the app, and Premium turns on after the payment is verified. See the <a href='premium.html'>Premium page</a>."),
 ("What happens when Premium ends?","Premium works for the plan length you paid for. After that the app is free again and ads come back."),
 ("Where is my data stored?","On your device. FocusLock does not upload your usage history to its own servers."),
 ("Does it work offline?","Yes. Limits, blocking and tracking work without internet. The internet is used for ads in the free version and for checking Premium payments."),
 ("Is there an iPhone version?","No. FocusLock is made for Android only."),
 ("How do I update FocusLock?","Download the newest APK from the <a href='download.html'>download page</a> and install it over the old one."),
]

# ---------- pages ----------
plans = '<div class="grid" data-plans></div>'
STEPS = [("Select","Choose the apps you want to control."),("Set","Set a daily time limit for each one."),("Monitor","FocusLock tracks how long each app is used."),("Warn","You get a heads-up when a limit is close."),("Block","When time is up, a block screen covers the app."),("Decide","Stay locked in, or complete a challenge you chose to unlock.")]
steps_html = '<ol class="steps">' + ''.join(f'<li><span><b>{a}.</b> {b}</span></li>' for a,b in STEPS) + '</ol>'
page('index','FocusLock: App limits and focus for Android','Set daily limits for distracting apps, lock them when time is up, and unlock only on purpose. Free Android app, no account.',f'''
<section class="hero-s"><div class="w hero"><div><p class="eyebrow">Free for Android</p><h1>Take your time back from distracting apps.</h1><p class="lead">FocusLock puts a calm barrier between you and the apps that eat your day. Pick the apps, set the limits, and unlock only on purpose.</p><div class="row">{BTN('Download FocusLock')}<a class="btn g" href="features.html">Explore features</a></div><p class="note">Free · No account · <span data-cfg="android"></span></p></div>
<div class="duo hero-duo">{phone('home','FocusLock Home screen with focus score, streak and active limits',lazy=False)}{phone('block','FocusLock block screen shown during Focus mode',lazy=False)}</div></div></section>
<section class="tight"><div class="w stats"><div><b>4</b><span>Unlock challenges</span></div><div><b>6</b><span>App languages</span></div><div><b>6</b><span>Animated themes</span></div><div><b>0</b><span>Accounts needed</span></div></div></section>
<section><div class="w">{head2('Why FocusLock','Built to help, not to nag')}<div class="grid">{card('Your data stays on your phone','Limits, usage and goals are stored on the device. There is no sign-up.','🔒')}{card('Unlocking takes intent','Time is not just cut off. You choose a small challenge that gives you a moment to decide.','🎯')}{card('Safe by design','Calls and emergency functions are never blocked, and emergency bypasses exist.','🛟')}</div></div></section>
<section><div class="w">{head2('What it does','Everything you need, nothing you do not')}<div class="grid">{card('App time limits','Set a daily limit for each app. Use templates and schedules to save time.','⏱️')}{card('Automatic app locking','When the limit is reached, a block screen covers the app until you decide what to do.','🛡️')}{card('Focus mode','Lock distractions for a session from 15 minutes to 2 hours.','🧘')}{card('Unlock challenges','Math, patience countdown, typing a sentence, or your PIN.','🧩')}{card('Usage tracking','See screen time, insights, goals, streaks and trends.','📊')}{card('Themes and languages','Six animated themes and six app languages, including Bangla.','🎨')}</div><div class="row"><a class="btn g" href="features.html">See every feature</a></div></div></section>
<section><div class="w">{head2('How it works','Six simple steps')}{steps_html}</div></section>
<section><div class="w">{head2('App tour','See FocusLock in action','Real screens from the app. <a href="tour.html">Take the full tour</a>.')}<div class="rail" tabindex="0" aria-label="App screenshots">{shot('home','Home','FocusLock Home screen')}{shot('apps','App Limits','FocusLock App Limits screen listing apps with switches')}{shot('focus','Focus Mode','FocusLock Focus Mode timer screen')}{shot('block','Block screen','FocusLock block screen')}{shot('stats','Stats','FocusLock screen time and stats')}{shot('settings','Settings','FocusLock Settings screen')}</div></div></section>
<section><div class="w split"><div class="prose">{head2('Unlock challenges','A pause that works','When you want more time, you complete a short challenge you turned on. It is just enough friction to ask: do I really need this?')}<ul><li>Mental math</li><li>Patience and stillness countdown</li><li>Mindful typing of a sentence</li><li>Your own PIN</li></ul><a class="btn g" href="features.html#challenges">How challenges work</a></div><div class="duo three">{phone('math','Mental math unlock challenge')}{phone('patience','Patience countdown unlock challenge')}{phone('typing','Mindful typing unlock challenge')}</div></div></section>
<section><div class="w">{head2('Premium','Remove ads, keep everything else','The free app shows ads. Premium turns them off. Pay with USDT through Binance Pay.')}{plans}<div class="row"><a class="btn g" href="premium.html">See how Premium works</a></div></div></section>
<section><div class="w privacy-band"><div>{head2('Privacy first','No account. No upload of your usage.')}<p>FocusLock keeps your data on your device and asks only for the permissions it needs to do its job.</p><a class="btn g" href="privacy.html">Read the privacy page</a></div><ul class="ticks"><li>No sign-up or login</li><li>Usage data stays on the phone</li><li>Calls and emergencies never blocked</li><li>You can see why each permission is needed</li></ul></div></section>
<section><div class="w prose">{head2('FAQ','Quick answers')}{''.join(det(q,a) for q,a in FAQ[:5])}<a class="btn g" href="faq.html">More questions</a></div></section>
<section><div class="w">{head2('Blog','Latest from the blog')}<div class="grid" id="latest"></div></div></section>{CTA}''',blog=True)

page('features','FocusLock Features: limits, locking, challenges, tracking','Everything FocusLock does: app time limits, automatic locking, unlock challenges, Focus mode, usage tracking, notifications, themes and privacy.',f'''
<section><div class="w"><p class="eyebrow">Features</p><h1>What FocusLock can do</h1><p class="lead">A focused set of tools, all in the app today. Jump to: <a href="#limits">Limits</a> · <a href="#locking">Locking</a> · <a href="#challenges">Challenges</a> · <a href="#tracking">Tracking</a> · <a href="#notifications">Notifications</a> · <a href="#custom">Customization</a> · <a href="#privacy">Privacy</a></p></div></section>
<div id="limits">{row('App time limits','Set a limit for each app','<ul><li>Every installed app is listed, with a search box</li><li>Filter by All, Limits or Blocked</li><li>A switch and a daily limit for each app</li><li>Apps that tend to eat time are tagged Distracting</li><li>Templates and schedules save setup time</li><li>A warning comes before the limit is reached</li></ul>',phone('apps','FocusLock App Limits screen'))}</div>
<div id="locking">{row('Automatic locking','A block screen, not a surprise','<p>FocusLock notices which app is open. When a limit is reached, or a Focus session is running, a block screen covers the app.</p><ul><li><b>Stay Locked In</b> closes the app and takes you home</li><li><b>Complete Challenge to Unlock</b> opens your chosen challenge</li><li><b>Emergency Bypass</b> gives short access for something urgent, with a daily limit</li></ul>',phone('block','FocusLock block screen with unlock options'),True)}</div>
<div>{row('Focus mode','Deep work sessions','<p>Pick a length from 15 minutes to 2 hours and press Lock In. Distracting apps stay blocked until the timer ends. With your permission, FocusLock can also use Do Not Disturb to quiet notifications.</p>',phone('focus','FocusLock Focus Mode timer'))}</div>
<div id="challenges"><section><div class="w">{head2('Unlock challenges','Four ways to earn more time','Choose which ones are on. Each one adds a short pause before you open a limited app.')}<div class="grid">{card('Mental math','Solve a quick sum to continue.')}{card('Patience and stillness','Wait out a 30-second countdown. You can give up at any time.')}{card('Mindful typing','Type a sentence exactly. This unlocks 5 extra minutes.')}{card('PIN','Enter a PIN that you set.')}</div><div class="duo three" style="margin-top:32px">{phone('math','Mental math challenge')}{phone('patience','Patience and stillness challenge')}{phone('typing','Mindful typing challenge')}</div></div></section></div>
<div id="tracking">{row('Usage tracking','Know where your time goes','<ul><li>Analytics, Insights and Goals tabs</li><li>View Today, Yesterday or This Week</li><li>Total usage, focus time and blocked apps</li><li>Focus streak with milestones at 3, 7, 14 and 30 days</li><li>Daily screen time trend</li><li>Levels and XP for staying on track</li></ul>',phone('stats','FocusLock Stats screen'),True)}</div>
<section id="notifications"><div class="w prose">{head2('Notifications','Warnings you can act on')}<p>FocusLock tells you when you are close to a limit and when an app has been locked. You can manage alerts from Settings.</p></div></section>
<div id="custom">{row('Customization','Make it yours','<ul><li>Animated background themes: Cherry Blossom, Sakura Lake, Autumn Leaves, Cyber Rain, Aurora Forest and Deep Ocean</li><li>Six languages: English, Bangla, Spanish, French, Arabic and Portuguese</li><li>Backup and restore from Settings</li></ul>',phone('themes','FocusLock animated themes picker')+phone('settings','FocusLock Settings screen'))}</div>
<section id="privacy"><div class="w prose">{head2('Privacy','Your data stays with you')}<p>No account is needed. Limits, usage and goals are stored on your device. The permissions FocusLock asks for are explained on the <a href="privacy.html">privacy page</a>.</p></div></section>{CTA}''')

TOUR = [('Home','Your day at a glance','The Home screen shows today\'s usage, your Focus Score, time reclaimed, active limits and your streak. A banner tells you if a permission is missing.','home','FocusLock Home screen'),
('Choose apps and set limits','Pick what to control','Open Apps, find an app, and switch it on. Set how long you want to allow each day.','apps','FocusLock Apps screen'),
('Focus mode','Lock in for a session','Choose 15 minutes to 2 hours. Distracting apps stay blocked until the timer ends.','focus','FocusLock Focus Mode'),
('Track your time','See the trend','Stats shows today\'s usage, focus time, blocked apps, your streak and the daily trend. Insights and Goals are one tap away.','stats','FocusLock Stats'),
('The block screen','When time is up','FocusLock covers the app. Stay locked in, complete a challenge, or use an emergency bypass.','block','FocusLock block screen'),
('Unlock challenges','Earn extra time on purpose','Solve a math question, wait out a countdown, or type a sentence exactly.','math','FocusLock math challenge'),
('Settings and themes','Make it yours','Pick an animated theme, change language, manage notifications and Focus mode, and see your emergency bypasses.','settings','FocusLock Settings'),
('Premium','Remove the ads','Choose a plan, pay with Binance Pay and enter the transaction ID. Premium removes ads.','premium','FocusLock Premium screen')]
tour_rows = ''.join(f'<section><div class="w split{" rev" if i%2 else ""}"><div class="prose"><p class="eyebrow">Step {i+1}</p><h2>{h}</h2><h3 class="sub">{s}</h3><p>{p}</p></div><div class="duo">{phone(n,a)}</div></div></section>' for i,(h,s,p,n,a) in enumerate(TOUR))
page('tour','FocusLock App Tour: see every screen','A step-by-step tour of FocusLock with real screenshots: Home, app limits, Focus mode, stats, block screen, challenges, settings and Premium.',f'<section><div class="w"><p class="eyebrow">App tour</p><h1>Tour the app</h1><p class="lead">From picking apps to unlocking with a challenge. These are real screens from FocusLock.</p></div></section>{tour_rows}{CTA}')

PERMS = [("Usage access","Measures how long each app is used.","Required"),("Accessibility service","Detects which app is open so the block screen can appear. It is not used to read messages or passwords.","Required"),("Display over other apps","Shows the block screen on top of a limited app.","Required"),("Notifications","Limit warnings and focus alerts.","Recommended"),("Do Not Disturb access","Quiets notifications during Focus mode.","Optional"),("Internet","Ads in the free version and Premium payment checks.","Needed for ads and payments")]
perm_table = '<div class="tw"><table class="tbl"><thead><tr><th>Permission</th><th>Why it is needed</th><th>Status</th></tr></thead><tbody>' + ''.join(f'<tr><td><b>{a}</b></td><td>{b}</td><td>{c}</td></tr>' for a,b,c in PERMS) + '</tbody></table></div>'
page('download','Download FocusLock for Android (APK)','Download the latest FocusLock APK for Android. Version, size, checksum, requirements, install and update steps, permissions and help.',f'''
<section><div class="w hero"><div><p class="eyebrow">Download</p><h1>Download FocusLock for Android</h1><p class="lead">Free. Get the APK, install it, and set your first limit in a minute.</p><div class="row"><a class="btn" data-apk href="{APK}">Download APK <span data-cfg="size"></span></a></div><p class="note">Download not starting? <a data-apk href="{APK}">Open the direct link</a>.</p></div><div class="grid two"><div class="card"><small>Version</small><h3><span data-cfg="version"></span> (build <span data-cfg="build"></span>)</h3></div><div class="card"><small>Size</small><h3 data-cfg="size"></h3></div><div class="card"><small>Released</small><h3 data-cfg="date"></h3></div><div class="card"><small>Requires</small><h3 data-cfg="android"></h3></div></div></div></section>
<section><div class="w prose">{head2('Install','Install in four steps')}<ol class="steps"><li><span>Tap Download APK. If your browser warns that this type of file can be harmful, choose to keep it.</span></li><li><span>Open the file. If asked, allow your browser or file manager to install unknown apps.</span></li><li><span>Install and open FocusLock.</span></li><li><span>Grant the permissions below when the app asks.</span></li></ol>
{head2('Update','Updating')}<p>Download the newest APK from this page and install it over the old version.</p>
{head2('Verify','Check the file (optional)')}<p>The SHA-256 checksum of this APK is below. Compare it with a checksum tool if you want to confirm the file is unchanged.</p><div class="card"><code id="sha" data-cfg="sha"></code><div class="row"><button class="btn g sm" type="button" data-copy="#sha">Copy checksum</button></div></div></div></section>
<section><div class="w">{head2('Permissions','What FocusLock asks for')}{perm_table}</div></section>
<section><div class="w prose">{head2('Release history','Versions')}<div class="card"><h3>v<span data-cfg="version"></span> · build <span data-cfg="build"></span></h3><p>Latest release, <span data-cfg="date"></span>. Source and releases are on <a data-gh href="{GH}">GitHub</a>.</p></div>
{head2('Help','Troubleshooting')}{det('The app will not install','Check that you have '+MINA+' and enough free space. Allow installs from unknown apps for your browser or file manager.')}{det('The block screen does not appear','Open Settings, then Permission Center, and make sure Usage access, Accessibility and Display over other apps are all granted.')}{det('The download does not start','Try another browser or network. You can also use the direct link above or get the file from <a data-gh href="'+GH+'">GitHub</a>.')}{det('Protection Limited banner on Home','This means a permission is missing, usually Accessibility. Tap Manage and turn it on.')}<p>More answers are on the <a href="faq.html">FAQ page</a>.</p></div></section>{CTA}''')

page('premium','FocusLock Premium: remove ads','FocusLock Premium removes ads for a cleaner, distraction-free experience. Weekly $0.29, Monthly $0.49, Quarterly $1.50, Yearly $5. Pay with Binance Pay.',f'''
<section><div class="w split"><div class="prose"><p class="eyebrow">Premium</p><h1>Remove the ads</h1><p class="lead">Premium removes advertisements from FocusLock. Nothing else changes. A cleaner app for a calmer mind.</p><div class="row"><a class="btn g" href="#plans">See plans</a></div></div><div class="duo">{phone('premium','FocusLock Premium plans screen',lazy=False)}</div></div></section>
<section id="plans"><div class="w">{head2('Plans','Pick a length')}{plans}</div></section>
<section><div class="w">{head2('Benefits','What you get')}<div class="grid">{card('No advertisements','All ads are removed while Premium is active.','🚫')}{card('A cleaner experience','Fewer things on screen.','✨')}{card('Distraction-free','Ads are the last thing a focus app should show.','🎯')}</div></div></section>
<section><div class="w prose">{head2('Free vs Premium','What changes')}<div class="tw"><table class="tbl"><thead><tr><th></th><th>Free</th><th>Premium</th></tr></thead><tbody><tr><td>App limits and locking</td><td>✓</td><td>✓</td></tr><tr><td>Focus mode</td><td>✓</td><td>✓</td></tr><tr><td>Unlock challenges</td><td>✓</td><td>✓</td></tr><tr><td>Usage tracking and stats</td><td>✓</td><td>✓</td></tr><tr><td>Themes and languages</td><td>✓</td><td>✓</td></tr><tr><td><b>Advertisements</b></td><td>Shown</td><td><b>Removed</b></td></tr></tbody></table></div></div></section>
<section><div class="w prose">{head2('Payment','How payment works','Payment is made with USDT through Binance Pay. Everything happens inside the app.')}<ol class="steps"><li><span><b>Choose a plan</b> in FocusLock.</span></li><li><span><b>Complete the Binance payment</b> for the exact amount shown.</span></li><li><span><b>Submit the transaction ID</b> in the app.</span></li><li><span>The payment is <b>verified</b>.</span></li><li><span>Premium is <b>activated</b>.</span></li></ol><p>This website never asks for payment details, keys or wallet credentials.</p>
{head2('FAQ','Premium questions')}{det('Does Premium add features?','No. Premium removes ads.')}{det('Which currency do I pay in?','USDT, through Binance Pay.')}{det('What happens when Premium ends?','The app is free again and ads come back.')}{det('My verification failed. What now?','Check the amount, the currency and the recipient, wait for Binance to finish the payment, then try again.')}{det('Can I get a refund?','See the refund section in the <a href="terms.html">terms</a>.')}</div></section>{CTA}''',{"@context":"https://schema.org","@type":"WebPage","name":"FocusLock Premium"})

page('blog','FocusLock Blog: focus and screen time tips','Articles about reducing screen time, building focus habits and getting more from FocusLock.','''
<section><div class="w"><p class="eyebrow">Blog</p><h1>Focus and screen time</h1><p class="lead">Short, practical reads.</p><label for="q" class="meta">Search articles</label><input id="q" type="search" placeholder="Search"><div class="pills" id="cats" role="group" aria-label="Categories"></div><div class="grid" id="list"></div><div class="row"><button class="btn g" id="more" type="button" hidden>Load more</button></div></div></section>'''+CTA,{"@context":"https://schema.org","@type":"Blog","name":"FocusLock Blog","url":D+"/blog.html"},True)

page('about','About FocusLock','FocusLock is a privacy-first Android app that helps you control distracting apps and build better digital habits. Learn why it exists and how it works.',f'''
<section><div class="w prose"><p class="eyebrow">About</p><h1>About FocusLock</h1><p class="lead">FocusLock is an Android app that puts a simple barrier between you and distracting apps.</p>
{head2('The problem','Apps are built to keep you scrolling')}<p>Feeds, short videos and games are designed to be hard to put down. Willpower alone often loses.</p>
{head2('Who it is for','Anyone who wants more control')}<p>Students, workers, creators and anyone who opens an app without meaning to.</p>
{head2('How it works','Limits, a block screen, a pause')}<p>You pick apps and set daily limits. FocusLock tracks usage, warns you, and covers the app with a block screen when time is up. To get more time you complete a challenge you chose.</p>{steps_html}
{head2('Mission','Make distraction harder, focus easier')}<p>Without taking control away from you.</p>
{head2('Philosophy','You set the rules')}<p>FocusLock helps you keep them when it matters.</p>
{head2('Privacy first','No account, data on your phone')}<p>There is no sign-up. Your limits and usage stay on your device. We do not need an account because nothing has to be synced. Read the <a href="privacy.html">privacy page</a>.</p>
{head2('Why Android','Where the tools are')}<p>FocusLock uses Android features such as usage access and the Accessibility service to see which app is open. That is why it is built for Android.</p>
{head2('Difference','What makes it different')}<ul><li>Unlocking takes a deliberate challenge you choose.</li><li>Usage data stays on your device.</li><li>Calls and emergencies are never blocked.</li><li>Six themes and six languages.</li></ul>
{head2('Developer','Made by Zihad')}<p>FocusLock is made by <a data-dev href="{DEV}">Zihad</a>. Source and releases: <a data-gh href="{GH}">GitHub</a>.</p>
{head2('Contact','Get in touch').replace('<h2>','<h2 id="contact">')}<p>Email: <a data-mail href="#"><span data-cfg="email"></span></a></p></div></section>{CTA}''')

page('faq','FocusLock FAQ: answers to common questions','Answers about FocusLock: is it free, permissions, limits, unlock challenges, Premium, payment, privacy and updates.',f'<section><div class="w prose"><p class="eyebrow">FAQ</p><h1>Frequently asked questions</h1>{"".join(det(q,a) for q,a in FAQ)}<p>Still stuck? See <a href="about.html#contact">Contact</a>.</p></div></section>{CTA}',faq_ld(FAQ))

page('privacy','Privacy Policy | FocusLock','How FocusLock handles your data: what stays on your device, permissions, ads, and Premium payment checks.',f'''
<section><div class="w"><p class="eyebrow">Privacy</p><h1>Your privacy</h1><p class="lead">The short version first, then the full policy. Items marked [CONFIG] depend on your setup and must be reviewed before launch.</p>
<div class="grid">{card('No account','There is no sign-up or login.','👤')}{card('Data on your device','Limits, usage and goals are stored locally.','📱')}{card('No usage upload','FocusLock does not upload your usage history to its own servers.','🔒')}{card('Calls stay open','Phone and emergency functions are never blocked.','📞')}</div></div></section>
<section><div class="w">{head2('Permissions','What FocusLock can access, and why')}{perm_table}</div></section>
<section><div class="w prose"><h2>Full policy</h2>
<h3>Information collected</h3><p>FocusLock stores your app limits, usage statistics, goals, streaks and settings in a local database on your device.</p>
<h3>Information not collected</h3><p>FocusLock does not read your messages, passwords or keystrokes, and does not upload your usage history to its own servers. Analytics collection is turned off in the app.</p>
<h3>App usage and accessibility data</h3><p>The Accessibility service is used to detect which app is in the foreground so the block screen can appear.</p>
<h3>Local storage and backups</h3><p>Data stays on your device. If you export a backup, the file is saved where you choose.</p>
<h3>Data deletion</h3><p>Uninstalling the app removes its local data from your device. [CONFIG: confirm backup-file handling]</p>
<h3>Advertising</h3><p>The free version shows ads from Adsterra in embedded web views. Adsterra may collect data under its own policy. Premium removes ads. [CONFIG: confirm ad partners]</p>
<h3>Premium and payment information</h3><p>Payments are made in Binance Pay. When you submit a transaction ID, the app checks it with Binance. FocusLock does not receive your Binance login. Premium expiry and used transaction IDs are stored on your device.</p>
<h3>Third-party services</h3><p>Adsterra (ads) and Binance (payment checks).</p>
<h3>Data security</h3><p>Data is kept on your device and protected by Android. No method is completely secure.</p>
<h3>Children's privacy</h3><p>FocusLock is not directed to children under 13. [CONFIG: review for your region]</p>
<h3>Changes</h3><p>We may update this policy and will change the date below.</p><p>Last updated: <span data-cfg="date"></span></p>
<h3>Contact</h3><p><a data-mail href="about.html#contact"><span data-cfg="email"></span></a></p></div></section>''')

page('terms','Terms of Service | FocusLock','Terms for using FocusLock, including Premium purchases, Binance payment verification and refunds.','''
<section><div class="w prose"><p class="eyebrow">Terms</p><h1>Terms of service</h1><p>Items marked [CONFIG] must be completed before launch.</p>
<h2>Acceptance of terms</h2><p>By using FocusLock you agree to these terms.</p><h2>Using FocusLock</h2><p>You may use FocusLock for personal digital wellbeing. You choose which apps and protections to enable.</p>
<h2>App functionality</h2><p>FocusLock limits and blocks apps you select. Optional protections can make it harder to disable the app during a session. Calls and emergency functions are not blocked.</p>
<h2>Premium purchases</h2><p>Premium removes ads for the plan length: 7, 30, 90 or 365 days. Prices are shown in the app and on the Premium page.</p>
<h2>Binance payment verification</h2><p>Pay the exact USDT amount through Binance Pay, then submit the transaction ID in the app. Premium activates after the payment is verified.</p>
<h2>Refund policy</h2><p>[CONFIG: add your refund policy here]</p>
<h2>Premium entitlement</h2><p>Premium is stored on your device and is active until the end of the plan period.</p>
<h2>Acceptable use</h2><p>Do not misuse FocusLock, tamper with payment checks, or reuse transaction IDs.</p>
<h2>Disclaimer</h2><p>FocusLock is provided as is, without warranties. It is a productivity tool and not medical advice.</p><h2>Changes to terms</h2><p>We may update these terms. Continued use means you accept them.</p>
<h2>Contact</h2><p><a data-mail href="about.html#contact"><span data-cfg="email"></span></a></p></div></section>''')

# ---------- blog posts: (slug, title, description, category, date, cover, html) ----------
P = lambda *x: ''.join(x)
POSTS = [
('reduce-screen-time','7 simple ways to reduce screen time','Practical steps to spend less time on distracting apps, and how app limits can help.','Habits','2026-09-20','bg-aurora',
 '<p>Most of us do not plan to lose an hour to a feed. It just happens. These steps make that harder.</p><h2>1. Pick the apps that cost you most</h2><p>Check your usage and choose the two or three apps that eat the most time. Start there.</p><h2>2. Set a daily limit per app</h2><p>A limit turns a vague wish into a number. In FocusLock you set a daily limit for each app you choose.</p><h2>3. Add friction</h2><p>When the limit is reached, make opening the app slower. See <a href="why-unlocking-should-take-effort.html">why unlocking should take effort</a>.</p><h2>4. Protect blocks of deep work</h2><p>Plan focus sessions. Read <a href="run-a-deep-focus-session.html">how to run a deep focus session</a>.</p><h2>5. Track it weekly</h2><p>Look at your trend once a week. Small drops add up.</p><h2>6. Keep emergencies easy</h2><p>Real needs should never be blocked. FocusLock never blocks calls and has daily emergency bypasses.</p><h2>7. Be kind to yourself</h2><p>Some days you will go over. Reset and try again tomorrow.</p>'),
('why-unlocking-should-take-effort','Why unlocking an app should take a little effort','A short pause between the urge and the app is often enough to change your mind.','Focus','2026-09-22','bg-cyber',
 '<p>Impulse opens are fast. A small barrier slows them down enough for you to ask: do I really want this?</p><h2>Make the pause useful</h2><p>FocusLock offers four unlock challenges: a math question, a 30-second patience countdown, typing a sentence exactly, or your own PIN. You choose which ones are on.</p><h2>Keep real emergencies easy</h2><p>FocusLock never blocks calls or emergency functions, and it has daily emergency bypasses for urgent needs.</p><p>Next: <a href="reduce-screen-time.html">7 ways to reduce screen time</a>.</p>'),
('run-a-deep-focus-session','How to run a deep focus session','A simple routine for 15 minutes to 2 hours of work without distractions.','Productivity','2026-09-24','bg-ocean',
 '<p>Deep work needs a clear start, a clear end, and fewer interruptions in between.</p><h2>Before you start</h2><p>Pick one task and one duration. FocusLock Focus mode lets you choose from 15 minutes to 2 hours.</p><h2>During the session</h2><p>Distracting apps stay blocked until the timer ends. With your permission, FocusLock can also use Do Not Disturb to quiet notifications.</p><h2>After</h2><p>Take a real break away from the screen, then plan the next one. See also <a href="reduce-screen-time.html">reduce screen time</a>.</p>'),
('how-app-limits-work-on-android','How app limits work on Android','What happens behind the scenes when an app limit is reached, and why FocusLock asks for certain permissions.','Android','2026-09-26','bg-sakura',
 '<p>An app limit has three jobs: measure time, notice the app, and show a block screen.</p><h2>1. Measuring time</h2><p>Android shares app usage with apps that you allow. In FocusLock this is called Usage access.</p><h2>2. Noticing the app</h2><p>The Accessibility service tells FocusLock which app is in front. FocusLock uses it only for that.</p><h2>3. Showing the block screen</h2><p>With permission to display over other apps, FocusLock covers the limited app.</p><p>See every permission on the <a href="../privacy.html">privacy page</a>, or follow <a href="set-your-first-limit-in-focuslock.html">the first-limit guide</a>.</p>'),
('avoid-endless-scrolling','How to avoid endless scrolling','Feeds have no end on purpose. Here is how to add one yourself.','Habits','2026-09-28','bg-cyber',
 '<p>A feed never says "that is all". You have to say it.</p><h2>Decide the stop before you start</h2><p>Choose a time or a number of posts before you open the app.</p><h2>Use a limit as your stop</h2><p>A daily limit ends the session for you. See <a href="choosing-the-right-daily-limit.html">choosing the right daily limit</a>.</p><h2>Move the app out of reach</h2><p>Put it in a folder or off the home screen.</p><h2>Notice the habit</h2><p>If you open an app without deciding to, that is the habit to work on. A short challenge before unlocking helps you notice it.</p>'),
('build-a-focused-android-setup','How to build a focused Android setup','A few settings that make your phone calmer.','Android','2026-09-30','bg-aurora',
 '<h2>Clean the home screen</h2><p>Keep only the apps you use on purpose.</p><h2>Turn off notifications you do not need</h2><p>Keep calls and messages from people. Silence the rest.</p><h2>Add limits to the usual suspects</h2><p>Use <a href="set-your-first-limit-in-focuslock.html">FocusLock limits</a> for video, social and games.</p><h2>Use Focus mode for work</h2><p>See <a href="run-a-deep-focus-session.html">how to run a deep focus session</a>.</p>'),
('set-your-first-limit-in-focuslock','How to set your first limit in FocusLock','A step-by-step guide to installing FocusLock and setting your first app limit.','Tutorials','2026-10-01','bg-ocean',
 '<ol><li>Download FocusLock from the <a href="../download.html">download page</a> and install it.</li><li>Grant the permissions the app asks for: Usage access, Accessibility and Display over other apps.</li><li>Open the Apps tab and find an app you want to control.</li><li>Switch it on and set a daily limit.</li><li>Open Settings and choose the unlock challenges you want.</li></ol><p>That is it. When the limit is reached, a block screen appears. See the <a href="../tour.html">app tour</a> for every screen.</p>'),
('choosing-the-right-daily-limit','Choosing the right daily limit','Too strict and you give up. Too loose and nothing changes.','Productivity','2026-10-02','bg-sakura',
 '<h2>Start from your real number</h2><p>Look at how long you use the app today. Your first limit is a little less than that.</p><h2>Lower it in small steps</h2><p>Reduce the limit each week, not all at once.</p><h2>Use different limits for different apps</h2><p>An app you need for work gets a different limit than a game.</p><h2>Review the trend</h2><p>The Stats screen shows your daily trend. Adjust if you keep hitting the limit early.</p><p>Related: <a href="avoid-endless-scrolling.html">avoid endless scrolling</a>.</p>'),
('using-streaks-to-stay-consistent','Using streaks to stay consistent','A streak is a simple way to keep a habit going.','Habits','2026-10-03','bg-cyber',
 '<p>FocusLock tracks a focus streak: finish a focus session each day to grow it.</p><h2>Start small</h2><p>One 15-minute session counts as a start.</p><h2>Aim for the first milestones</h2><p>The app shows milestones at 3, 7, 14 and 30 days.</p><h2>If you miss a day</h2><p>Begin again. Consistency over time matters more than a perfect record.</p><p>Plan your sessions with <a href="run-a-deep-focus-session.html">this routine</a>.</p>'),
('phone-free-mornings-and-evenings','Phone-free mornings and evenings','Small boundaries around the start and end of your day.','Digital Wellbeing','2026-10-04','bg-aurora',
 '<p>This is general advice about habits, not medical advice.</p><h2>Mornings</h2><p>Wait before opening social apps. Start with something offline.</p><h2>Evenings</h2><p>Pick a time to put distracting apps away. Use a schedule or <a href="run-a-deep-focus-session.html">Focus mode</a> if it helps.</p><h2>Keep it realistic</h2><p>One boundary you keep beats five you do not. Also read <a href="reduce-screen-time.html">7 ways to reduce screen time</a>.</p>'),
]
def post_page(p):
    s,t,d,c,dt,im,body = p; path=f'posts/{s}.html'
    ld={"@context":"https://schema.org","@type":"Article","headline":t,"description":d,"datePublished":dt,"image":f"{D}/assets/images/{im}.webp","author":{"@type":"Person","name":"Zihad"},"publisher":{"@type":"Organization","name":"FocusLock"},"mainEntityOfPage":f"{D}/{path}"}
    cta = CTA.replace('href="tour.html"','href="../tour.html"')
    return head(f'{t} | FocusLock Blog',d,path,ld,'../','article')+header('blog','../')+f'<article><section><div class="w prose"><p class="meta">{c} · {dt}</p><h1 style="font-size:clamp(2rem,5vw,3rem)">{t}</h1><img src="../assets/images/{im}.webp" alt="" width="540" height="300" style="width:100%;height:260px;object-fit:cover;border-radius:18px;margin:20px 0">{body}<p><a href="../blog.html">← All articles</a></p></div></section></article><section><div class="w"><h2>Related articles</h2><div class="grid" id="related"></div></div></section>'+cta+footer('../',True)
os.makedirs('posts',exist_ok=True)
for f in os.listdir('posts'):
    if f.endswith('.html'): os.remove('posts/'+f)
for p in POSTS: open(f'posts/{p[0]}.html','w').write(post_page(p))
json.dump([{"title":p[1],"slug":p[0],"description":p[2],"category":p[3],"date":p[4],"image":f"assets/images/{p[5]}.webp","url":f"posts/{p[0]}.html"} for p in POSTS],open('data/posts.json','w'),indent=2)
urls=[''if k=='index' else k+'.html' for k,_ in NAV]+['faq.html','privacy.html','terms.html']+['posts/'+p[0]+'.html' for p in POSTS]
open('sitemap.xml','w').write('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{D}/{u}</loc></url>' for u in urls)+'</urlset>')
open('robots.txt','w').write(f'User-agent: *\nAllow: /\nSitemap: {D}/sitemap.xml\n')
json.dump({"name":"FocusLock","short_name":"FocusLock","start_url":"/","display":"standalone","background_color":"#070b12","theme_color":"#070b12","icons":[{"src":"assets/icons/icon-192.png","sizes":"192x192","type":"image/png"},{"src":"assets/icons/icon-512.png","sizes":"512x512","type":"image/png"}]},open('manifest.json','w'),indent=2)
print('built',len(urls),'urls')
